version: 2.1 jobs: build: docker:

      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: 最初のステップ
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: コードの取得
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
